[build]
  command = "yarn prod"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404

[[redirects]]
  from = "/ghost/*"
  to = "https://cms.1900.live/ghost/:splat"
  status = 301
  force = true