name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        uses: TartanLlama/actions-eleventy@master

      - name: Set Node.js 20.x
        uses: actions/setup-node@master
        with:
          node-version: 20.x        

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: prod # will run `yarn prod` command

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_dir: dist 
      #     publish_branch: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          build_directory: dist
        with:
          args: deploy --prod

# name: Build and Deploy

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: 14

#       - name: Install dependencies
#         run: yarn install

#       - name: Build
#         run: yarn prod

#       - name: Deploy to Netlify
#         uses: netlify/actions/cli@master
#         env:
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#         with:
#           args: deploy --prod
